# Generated by Django 3.1.4 on 2021-08-13 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
