# Generated by Django 3.1.4 on 2021-08-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='composition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.JSONField(default=list),
        ),
    ]
