# Generated by Django 3.1.4 on 2021-08-17 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.PositiveSmallIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
