# Generated by Django 3.1.4 on 2021-08-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='Заказ №<built-in function id>', max_length=50),
        ),
    ]
