# Generated by Django 3.1.4 on 2021-08-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
    ]
