# Generated by Django 3.1.4 on 2021-08-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(default='Заказ №<built-in function id>', max_length=20),
        ),
    ]
