# Generated by Django 3.1.4 on 2021-12-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='note',
        ),
    ]
